// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbOO5dKhoiF8kmDrnbigTKsTmj_8xSPDg',
    appId: '1:132894885676:web:659f463a6d8ac6aa3ece89',
    messagingSenderId: '132894885676',
    projectId: 'musicplayerz-63f2e',
    authDomain: 'musicplayerz-63f2e.firebaseapp.com',
    databaseURL: 'https://musicplayerz-63f2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicplayerz-63f2e.appspot.com',
    measurementId: 'G-ES189ZW8QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqL2eDQ3jcssbQVQMaLCSmagG5ZqNPk4E',
    appId: '1:132894885676:android:d3bd4cb7b9b07ce63ece89',
    messagingSenderId: '132894885676',
    projectId: 'musicplayerz-63f2e',
    databaseURL: 'https://musicplayerz-63f2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicplayerz-63f2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp7Tpm9m7iOCt4BPmDojGULrsWedWXmkk',
    appId: '1:132894885676:ios:a922404cd85288db3ece89',
    messagingSenderId: '132894885676',
    projectId: 'musicplayerz-63f2e',
    databaseURL: 'https://musicplayerz-63f2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicplayerz-63f2e.appspot.com',
    iosClientId: '132894885676-25skfndv5f9c0300486aj8rfd602sqpn.apps.googleusercontent.com',
    iosBundleId: 'nhom24.doan2023199.appDacSan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp7Tpm9m7iOCt4BPmDojGULrsWedWXmkk',
    appId: '1:132894885676:ios:55342214b40ec56a3ece89',
    messagingSenderId: '132894885676',
    projectId: 'musicplayerz-63f2e',
    databaseURL: 'https://musicplayerz-63f2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicplayerz-63f2e.appspot.com',
    iosClientId: '132894885676-ofasldc49pkcl6pf4mklpjv33fosp9n4.apps.googleusercontent.com',
    iosBundleId: 'nhom24.doan2023199.appDacSan.RunnerTests',
  );
}
